#!/usr/bin/env node
/**
 * Regenerates public/art/art-manifest.json from the PNGs actually present in
 * public/art/modules/. Run after adding/removing final art:
 *   npm run scan:art
 * Filenames must be sprite keys: <kindId>_<w>x<h>_<themeId>.png — anything
 * that doesn't match a real kind×size×theme combination fails the scan, so a
 * typo can't silently ship a placeholder. Exits nonzero on failure.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const modules = read('src/content/modules.json');
const themes = read('src/content/themes.json');
const validSpriteKeys = new Set();
for (const kind of modules.kinds ?? []) {
  for (const { w, h } of kind.sizes ?? []) {
    for (const theme of themes.themes ?? []) {
      validSpriteKeys.add(`${kind.id}_${w}x${h}_${theme.id}`);
    }
  }
}

const artDir = join(root, 'public/art/modules');
const files = existsSync(artDir)
  ? readdirSync(artDir).filter((f) => f.toLowerCase().endsWith('.png'))
  : [];

const keys = [];
const invalid = [];
for (const file of files) {
  const key = file.replace(/\.png$/i, '');
  (validSpriteKeys.has(key) ? keys : invalid).push(file);
}
if (invalid.length > 0) {
  console.error(`Art scan FAILED: ${invalid.length} file(s) in public/art/modules/ don't match any kind×size×theme:\n`);
  for (const f of invalid) console.error(`  ✗ ${f}`);
  console.error('\nExpected filenames like bedroom_3x1_tech.png. No manifest written.');
  process.exit(1);
}
keys.sort();

const manifestPath = 'public/art/art-manifest.json';
const previous = new Set(read(manifestPath).modules ?? []);
const manifest = {
  $comment:
    'AUTO-GENERATED by npm run scan:art — do not hand-edit the modules list. ' +
    'Drop a PNG at public/art/modules/<kindId>_<w>x<h>_<themeId>.png ' +
    '(exactly w*256 x h*256 px) to override that procedural sprite, then rerun the scan.',
  modules: keys,
};
writeFileSync(join(root, manifestPath), `${JSON.stringify(manifest, null, 2)}\n`);

const added = keys.filter((k) => !previous.has(k));
const removed = [...previous].filter((k) => !keys.includes(k));
console.log(`Art scan OK: ${keys.length} final-art override(s) (${added.length} added, ${removed.length} removed).`);
for (const k of added) console.log(`  + ${k}`);
for (const k of removed) console.log(`  - ${k}`);
